<?php
/*
--------------------------------------------------------------
My Handy Restaurant Configuration File
--------------------------------------------------------------
This file has been automatically generated by My Handy Restaurant

Edit it by hand only if you know what you're doing.
Otherwise use the install.php page.
---------------------------------------------------------------
*/

$cfgserver='localhost';
$cfguser='root';
$cfgpassword='';

$db_common='myhandyrestaurant';

$table_prefix='mhr_';

?>